#' Test cointegration for a pair of time series
#'
#' Applies the Johansen trace test to a pair of time series using
#' `urca::ca.jo()`, and returns the trace statistic for the null of no
#' cointegration together with an approximate significance level and the sample
#' correlation between the two series.
#'
#' @param pair Character or integer vector of length 2 identifying the two
#'   columns in `data` to use.
#' @param data A data frame or object coercible to a data frame containing the
#'   time-series variables.
#' @param lag Positive integer giving the lag order passed to `K` in
#'   `urca::ca.jo()`.
#' @param model Character scalar giving the deterministic specification used in
#'   the Johansen test. This is passed to `ecdet`, except that `"both"` is
#'   recoded to `"trend"`.
#'
#' @return A data frame with two rows:
#' \describe{
#'   \item{Estimate}{The Johansen trace statistic for the null of no
#'   cointegration (`"Trace0"`), and the sample correlation (`"Cor"`).}
#'   \item{Pval}{Approximate significance level for the trace statistic
#'   (`0.01`, `0.05`, `0.10`, or `1`), and `NA` for the correlation row.}
#'   \item{name}{Label identifying the returned statistic: `"Trace0"` or
#'   `"Cor"`.}
#' }
#'
#' @details
#' The function first subsets the requested pair of variables and removes
#' incomplete observations. It then applies `urca::ca.jo()` with
#' `type = "trace"` and evaluates the second reported trace statistic, which
#' corresponds to the null hypothesis of no cointegration.
#'
#' The reported `Pval` is not an exact p-value. Instead, it is a coarse
#' significance bucket based on the Johansen critical values:
#' \describe{
#'   \item{`0.01`}{reject at the 1% level}
#'   \item{`0.05`}{reject at the 5% level but not 1%}
#'   \item{`0.10`}{reject at the 10% level but not 5%}
#'   \item{`1`}{do not reject at the 10% level}
#' }
#' @export
trace_pair_test <- function(pair, data, lag, model) {
  x <- as.data.frame(data)[, pair, drop = FALSE]
  x <- x[stats::complete.cases(x), , drop = FALSE]

  jotest <- urca::ca.jo(
    x,
    type = "trace",
    K = lag,
    ecdet = ifelse(model %in% "both", "trend", model)
  )

  Pval <- ifelse(
    jotest@teststat[2] > jotest@cval[2, 3], 0.01,
    ifelse(
      jotest@teststat[2] > jotest@cval[2, 2], 0.05,
      ifelse(jotest@teststat[2] > jotest@cval[2, 1], 0.10, 1)
    )
  )

  jotest <- data.frame(
    Estimate = c(jotest@teststat[2], cor(x)[2]),
    Pval = c(Pval, NA),
    name = c("Trace0", "Cor")
  )

  return(jotest)
}



#' Hansen-Seo threshold cointegration test for a pair of series
#'
#' Applies the Hansen and Seo (2002) Sup-LM test for threshold cointegration
#' using `tsDyn::TVECM.HStest()`. The test evaluates the null hypothesis of
#' linear cointegration against the alternative of threshold cointegration in a
#' two-series system.
#'
#' @param pair Character or integer vector of length 2 identifying the two
#'   columns in `data` to use.
#' @param data A data frame or object coercible to a data frame containing the
#'   time-series variables.
#' @param lag Positive integer giving the lag order used in
#'   `tsDyn::TVECM.HStest()`. Default is `2`.
#' @param intercept Logical indicating whether an intercept is included in the
#'   threshold VECM. Default is `TRUE`.
#' @param nboot Positive integer giving the number of bootstrap replications
#'   used to compute the bootstrap p-value. Default is `100`.
#' @param trim Numeric scalar in `(0, 0.5)` giving the trimming proportion used
#'   in the threshold search. Default is `0.05`.
#' @param ngridTh Positive integer giving the number of threshold grid points
#'   used in the search. Default is `100`.
#' @param verbose Logical indicating whether to print a short message describing
#'   the test. Default is `TRUE`.
#'
#' @return A data frame with one row and three columns:
#' \describe{
#'   \item{Estimate}{The Hansen-Seo Sup-LM test statistic.}
#'   \item{Pval}{Bootstrap p-value returned by `tsDyn::TVECM.HStest()`.}
#'   \item{name}{Character label equal to `"HStest"`.}
#' }
#'
#' @details
#' The function first subsets the requested pair of variables and removes
#' incomplete observations. It then applies `tsDyn::TVECM.HStest()` to test
#' linear cointegration versus threshold cointegration.
#'
#' Output generated by `tsDyn::TVECM.HStest()` is suppressed using
#' `capture.output()`. A short console message is optionally printed when
#' `verbose = TRUE`.
#'
#' @references
#' Hansen, B. E., and Seo, B. (2002). Testing for two-regime threshold
#' cointegration in vector error-correction models. *Journal of Econometrics*,
#' 110(2), 293-318.
#'
#' @export
hansen_seo_threshold_test <- function(
    pair,
    data,
    lag = 2,
    intercept = TRUE,
    nboot = 100,
    trim = 0.05,
    ngridTh = 100,
    verbose = FALSE
) {
  if (length(pair) != 2) {
    stop("`pair` must identify exactly two columns.")
  }

  if (!is.numeric(lag) || length(lag) != 1 || lag < 1 || lag %% 1 != 0) {
    stop("`lag` must be a positive integer.")
  }

  if (!is.logical(intercept) || length(intercept) != 1 || is.na(intercept)) {
    stop("`intercept` must be a single TRUE/FALSE value.")
  }

  if (!is.numeric(nboot) || length(nboot) != 1 || nboot < 1 || nboot %% 1 != 0) {
    stop("`nboot` must be a positive integer.")
  }

  if (!is.numeric(trim) || length(trim) != 1 || trim <= 0 || trim >= 0.5) {
    stop("`trim` must be a numeric scalar strictly between 0 and 0.5.")
  }

  if (!is.numeric(ngridTh) || length(ngridTh) != 1 || ngridTh < 1 || ngridTh %% 1 != 0) {
    stop("`ngridTh` must be a positive integer.")
  }

  if (!is.logical(verbose) || length(verbose) != 1 || is.na(verbose)) {
    stop("`verbose` must be a single TRUE/FALSE value.")
  }

  x <- as.data.frame(data)[, pair, drop = FALSE]
  x <- x[stats::complete.cases(x), , drop = FALSE]

  if (nrow(x) == 0) {
    stop("No complete observations remain after removing missing values.")
  }

  if (verbose) {
    cat(
      crayon::black(
        "Test of linear cointegration versus threshold cointegration following Hansen and Seo (2002)"
      ),
      fill = TRUE
    )
  }

  capture.output(
    hs_test <- tsDyn::TVECM.HStest(
      x,
      lag = lag,
      ngridTh = ngridTh,
      nboot = nboot,
      trim = trim,
      fixed.beta = NULL,
      intercept = intercept
    )
  )

  return(data.frame(
    Estimate = hs_test$stat,
    Pval = hs_test$PvalBoot,
    name = "HStest"
  ))
}



#' Hansen linearity test against threshold autoregression for a pair of series
#'
#' Applies Hansen's (1999) likelihood ratio test of linearity versus threshold
#' autoregressive alternatives using `tsDyn::TVAR.LRtest()`. The function
#' evaluates both the one-versus-two regime and one-versus-three regime
#' threshold alternatives for a pair of time series.
#'
#' @param pair Character or integer vector of length 2 identifying the two
#'   columns in `data` to use.
#' @param data A data frame or object coercible to a data frame containing the
#'   time-series variables.
#' @param lag Positive integer giving the lag order used in
#'   `tsDyn::TVAR.LRtest()`. Default is `2`.
#' @param nboot Positive integer giving the number of bootstrap replications
#'   used to compute bootstrap p-values. Default is `100`.
#' @param thDelay Positive integer giving the threshold delay parameter.
#'   Default is `1`.
#' @param mTh Positive integer giving the number of threshold variables.
#'   Default is `1`.
#' @param trend Logical indicating whether to include a trend term in the test.
#'   Default is `TRUE`.
#' @param verbose Logical indicating whether to print a short message describing
#'   the test. Default is `TRUE`.
#'
#' @return A data frame with three columns:
#' \describe{
#'   \item{name}{Test label, either `"H1vs2"` or `"H1vs3"`.}
#'   \item{Estimate}{Likelihood ratio test statistic for the corresponding test.}
#'   \item{Pval}{Bootstrap p-value for the corresponding test.}
#' }
#'
#' @details
#' The function first subsets the requested pair of variables and removes
#' incomplete observations. It then applies `tsDyn::TVAR.LRtest()` with
#' `test = "1vs"` to evaluate:
#' \describe{
#'   \item{`"H1vs2"`}{linearity versus a two-regime threshold alternative}
#'   \item{`"H1vs3"`}{linearity versus a three-regime threshold alternative}
#' }
#'
#' Output generated by `tsDyn::TVAR.LRtest()` is suppressed using
#' `capture.output()`. A short console message is optionally printed when
#' `verbose = TRUE`.
#'
#' @references
#' Hansen, B. E. (1999). Testing for linearity. *Journal of Economic Surveys*,
#' 13(5), 551-576.
#'
#' @examples
#' \dontrun{
#' toy_data <- data.frame(
#'   market_1 = cumsum(rnorm(200)),
#'   market_2 = cumsum(rnorm(200))
#' )
#'
#' hansen_linearity_test(
#'   pair = c("market_1", "market_2"),
#'   data = toy_data,
#'   lag = 2,
#'   nboot = 100
#' )
#' }
#'
#' @export
hansen_linearity_test <- function(
    pair,
    data,
    lag = 2,
    nboot = 100,
    thDelay = 1,
    mTh = 1,
    trend = TRUE,
    verbose = TRUE
) {
  if (length(pair) != 2) {
    stop("`pair` must identify exactly two columns.")
  }

  if (!is.numeric(lag) || length(lag) != 1 || lag < 1 || lag %% 1 != 0) {
    stop("`lag` must be a positive integer.")
  }

  if (!is.numeric(nboot) || length(nboot) != 1 || nboot < 1 || nboot %% 1 != 0) {
    stop("`nboot` must be a positive integer.")
  }

  if (!is.numeric(thDelay) || length(thDelay) != 1 || thDelay < 1 || thDelay %% 1 != 0) {
    stop("`thDelay` must be a positive integer.")
  }

  if (!is.numeric(mTh) || length(mTh) != 1 || mTh < 1 || mTh %% 1 != 0) {
    stop("`mTh` must be a positive integer.")
  }

  if (!is.logical(trend) || length(trend) != 1 || is.na(trend)) {
    stop("`trend` must be a single TRUE/FALSE value.")
  }

  if (!is.logical(verbose) || length(verbose) != 1 || is.na(verbose)) {
    stop("`verbose` must be a single TRUE/FALSE value.")
  }

  x <- as.data.frame(data)[, pair, drop = FALSE]
  x <- x[stats::complete.cases(x), , drop = FALSE]

  if (nrow(x) == 0) {
    stop("No complete observations remain after removing missing values.")
  }

  if (verbose) {
    cat(
      crayon::black("Test of linearity versus threshold following Hansen (1999)"),
      fill = TRUE
    )
  }

  capture.output(
    Htest <- tsDyn::TVAR.LRtest(
      x,
      lag = lag,
      thDelay = thDelay,
      mTh = mTh,
      nboot = nboot,
      plot = FALSE,
      test = "1vs",
      trend = trend
    )
  )

  return(data.frame(
    name = c("H1vs2", "H1vs3"),
    Estimate = c(Htest$LRtest.val["1vs2"], Htest$LRtest.val["1vs3"]),
    Pval = c(Htest$Pvalueboot["1vs2"], Htest$Pvalueboot["1vs3"])
  ))
}

